### ISSUE TITLE
No page context

### ISSUE THREAD

**Issue by talkaboutdesign** [taming-the-state-in-react/nextjs-redux-firebase-authentication#11]
Sample is not working. Full error here: 

```
No page context
Error: No page context
    at Function._callee$ (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/next-redux-wrapper/lib/index.js:176:25)
    at tryCatch (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/next-redux-wrapper/lib/index.js:18:221)
    at _next (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/next-redux-wrapper/lib/index.js:18:409)
    at /Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/next-redux-wrapper/lib/index.js:18:477
    at new Promise (<anonymous>)
    at Function.<anonymous> (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/next-redux-wrapper/lib/index.js:18:97)
    at Function.value [as getInitialProps] (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/next-redux-wrapper/lib/index.js:218:25)
    at _callee$ (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/next/dist/lib/utils.js:86:30)
    at tryCatch (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/max/Downloads/nextjs-redux-firebase-authentication-master/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
```

**Comment by rwieruch** [comment]
We have two PRs for it, but no one bothered to review them:

https://github.com/taming-the-state-in-react/nextjs-redux-firebase-authentication/pull/4
https://github.com/taming-the-state-in-react/nextjs-redux-firebase-authentication/pull/7

Maybe you want to check them out? :)

**Comment by talkaboutdesign** [comment]
Worked for me.

**Comment by rwieruch** [comment]
Which one of them? :) Then I can merge one of them as fix to the project.

**Comment by aarohmankad** [comment]
Hey @rwieruch! #7 works perfectly for me :)

**Comment by rwieruch** [comment]
Perfect! Thanks for your reply 🚀
